import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Le blog de Lyon Palme",
  description: "Generated by create next app",
};

export const Header = () => (
  <header className="bg-purple-100 text-white p-4">
    <h1 className="text-2xl text-purple-600 font-bold">B2LP - Le blog de Lyon Palme</h1>
  </header>
);

export const Footer = () => (
  <footer className="bg-gray-100 text-center p-4 mt-10">
    <p className="text-sm text-purple-600 font-bold">Développé avec le ❤️ par les SIO2 - &copy; {new Date().getFullYear()}</p>
  </footer>
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
